CONTIKI_PROJECT = example-shell
all: $(CONTIKI_PROJECT)


APPS = serial-shell
CONTIKI = /home/user/Documents/book/contiki
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV4 = 1
include $(CONTIKI)/Makefile.include
