CONTIKI_PROJECT = shell-math-demo
all: $(CONTIKI_PROJECT)

APPS = serial-shell powertrace collect-view
CONTIKI = ../..

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include

