
CONTIKI_PROJECT = shell-demo
all: $(CONTIKI_PROJECT)

APPS = serial-shell powertrace collect-view
CONTIKI = /home/user/Documents/book/contiki
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
